unique_ids:
  forms: {Main: E6CAPCBSVDEAMI2VWEDDQDF7E2QNJL6S}
  modules: {AI: FAX5HGSWQ743UFD5P6REHBJK4FY3W4TG, Game: H5RO5RVL5CIYC4HUBHFLQBJ5L6VLXE7O}
  server_modules: {}
  assets: {standard-page.html: LZJ7OXVN72JZRH26ZV2DMUJIHQJJTALV, theme.css: HQXL7UENV77BMYJOO4QRUH74E2MMT56J}
